### ISSUE TITLE
Hierarchy of Resource Types

### ISSUE THREAD

**Issue by MaximilianV** [bptlab/rembrandt-backend#4]
As a developer, I'd like to have a dynamic and extensible hierarchy of resource types, so we can have specialized types while still being able to work on _superclass_ attributes.

### Hints
- When a new resource type is created, a predecessor must be chosen.
- Certain attributes are inherited.
- The new type can also be a new predecessor for a new resource type. (e.g. `programmer` is `employee` is `human resource`. A human has a _name_ attribute, an employee has a _salary_ attribute and a `programmer` has both plus a `programming languages` attribute.)

### Additional Questions To Answer
- Are all attributes of the predecessor inherited, or only a predefined set?

## Conditions of satisfaction

- [x] I've researched and decided on how resource types and their hierarchy could be stored.
- [x] I've documented the decision and the idea behind it in this issue.
- [x] I've answered the additional question and documented my findings.

**Comment by Munin33** [comment]
Resource Types and Instances have Meta-Types
ResourceType:
- name : string
- parentID: id
- ListOfAttributes:[Attr1:Type1; Attr2:type2]

ResourceInstance:
- name: string
- ResourcetypeID
-ListOfAttributes[value1:type1; value2:type2]


they are saved in mongodb in two seperate documents.

All parent attributes are inherited.
