### ISSUE TITLE
How to Program APIs

### ISSUE THREAD

**Issue by MaximilianV** [bptlab/rembrandt-backend#7]
As a developer, I'd like to have an understandable and consistent API implementation experience.

## Conditions of satisfaction

- [x] We've settled on a style how APIs will be implemented.
- [x] Each team member is informed and is able to add new API routes.

**Comment by friedow** [comment]
Would love to use https://jsonapi.org as a preset for api specification.

**Comment by friedow** [comment]
There is library support that helps to convert javascript objects to jsonapi responses and the other way around. Possible libraries, which serialize and deserialize jsonapi objects are:
- [jsonapi-serializer](https://www.npmjs.com/package/jsonapi-serializer) - Typescript support, community endorsement
- [json-api-serializer](https://www.npmjs.com/package/json-api-serializer) - No Typescript support, extensive customizability
